// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.startupRolloutPrefs.extensions.blocklist.useMLBF", true);
user_pref("app.normandy.startupRolloutPrefs.extensions.blocklist.useMLBF.stashes", true);
user_pref("app.normandy.user_id", "04b2972e-0ae0-4be1-8d88-0c5299f75f50");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1601398820);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1601397523);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1601398796);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1601398850);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 826);
user_pref("browser.cache.disk.capacity", 327680);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1601397495);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{433c0cec-aed8-4bb8-8bed-4796ecb8bf9e}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1601397516930");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1601401116930");
user_pref("browser.search.region", "AR");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200720193547");
user_pref("browser.slowStartup.averageTime", 7182);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20200720193547");
user_pref("browser.startup.homepage_override.mstone", "79.0");
user_pref("browser.startup.lastColdStartupCheck", 1601398792);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1601398803798");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "79.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "de551c84b50944898ccd0d6cd4cd3abd");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200720193547");
user_pref("extensions.lastAppVersion", "79.0");
user_pref("extensions.lastPlatformVersion", "79.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"79b56f70-3533-416e-a233-0068383bed6e\",\"formautofill@mozilla.org\":\"72356b1f-f73c-449c-9383-2f2621bd735e\",\"screenshots@mozilla.org\":\"93b36464-6269-4df3-821c-fb89567724f0\",\"webcompat-reporter@mozilla.org\":\"7f5c7117-088e-4f23-b949-22aba6c57155\",\"webcompat@mozilla.org\":\"5085c4d7-e4ef-4320-9145-262884ef4c58\",\"default-theme@mozilla.org\":\"bbf34a42-b80a-4850-b0f0-3235719eaaf3\",\"google@search.mozilla.org\":\"2922d756-9822-421d-afbc-d13087c0f303\",\"amazondotcom@search.mozilla.org\":\"eb555e36-1872-4bd7-9025-6a105d94c734\",\"wikipedia@search.mozilla.org\":\"56874e0d-5aca-4ab5-9069-d3f05d688c30\",\"bing@search.mozilla.org\":\"ffb2e798-918f-485f-9810-bbe9bf7a72af\",\"ddg@search.mozilla.org\":\"196f114f-94f0-46b2-ad05-4f451609ed7b\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1601398840);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20200720193547");
user_pref("media.gmp-manager.lastCheck", 1601398831);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 85463);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.remote_settings.crlite_filters.checked", 1601398829);
user_pref("security.remote_settings.intermediates.checked", 1601398829);
user_pref("security.sandbox.content.tempDirSuffix", "61e4b6be-b336-426b-ae70-be4c255693ac");
user_pref("security.sandbox.plugin.tempDirSuffix", "f92576f2-87d3-4904-b56b-7d8444089bbf");
user_pref("services.blocklist.addons-mlbf.checked", 1601398829);
user_pref("services.blocklist.gfx.checked", 1601398829);
user_pref("services.blocklist.pinning.checked", 1601398829);
user_pref("services.blocklist.plugins.checked", 1601398829);
user_pref("services.settings.clock_skew_seconds", 1);
user_pref("services.settings.last_etag", "\"1601398279412\"");
user_pref("services.settings.last_update_seconds", 1601398829);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1601398829);
user_pref("services.settings.main.cfr-fxa.last_check", 1601398829);
user_pref("services.settings.main.cfr.last_check", 1601398829);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1601398829);
user_pref("services.settings.main.hijack-blocklists.last_check", 1601398829);
user_pref("services.settings.main.language-dictionaries.last_check", 1601398829);
user_pref("services.settings.main.message-groups.last_check", 1601398829);
user_pref("services.settings.main.messaging-experiments.last_check", 1601398829);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1601398829);
user_pref("services.settings.main.pioneer-study-addons.last_check", 1601398829);
user_pref("services.settings.main.public-suffix-list.last_check", 1601398829);
user_pref("services.settings.main.search-config.last_check", 1601398829);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1601398829);
user_pref("services.settings.main.sites-classification.last_check", 1601398829);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1601398829);
user_pref("services.settings.main.whats-new-panel.last_check", 1601398829);
user_pref("services.settings.security.onecrl.checked", 1601398829);
user_pref("toolkit.startup.last_success", 1601398788);
user_pref("toolkit.telemetry.cachedClientID", "8170725d-282b-4bfd-9b0e-1cd18ffcfe11");
user_pref("toolkit.telemetry.pioneer-new-studies-available", true);
user_pref("toolkit.telemetry.previousBuildID", "20200720193547");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
